### ISSUE TITLE
钉钉同步报错

### ISSUE THREAD

**Issue by xzzgwzh** [programmer-zheng/virtual-ldap#1]
Error.
An error occurred while processing your request.
Request ID: 00-6bafd415217e91c5f9790359bdf1e9b7-e7b1ed464cb2d30c-00

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

**Comment by xzzgwzh** [comment]
Provider init complete...
virtual-ldap listening at ldap://0.0.0.0:389
Reload entries from provider
Reload entries from Dingtalk
init department and user data
server api(/departments) could not be request,please check server api

**Comment by xzzgwzh** [comment]
两处报错，请问是什么原因

**Comment by programmer-zheng** [comment]
> Provider init complete... virtual-ldap listening at ldap://0.0.0.0:389 Reload entries from provider Reload entries from Dingtalk init department and user data server api(/departments) could not be request,please check server api

后端服务报错，ldap服务无法正常请求后端接口

**Comment by programmer-zheng** [comment]
> Error. An error occurred while processing your request. Request ID: 00-6bafd415217e91c5f9790359bdf1e9b7-e7b1ed464cb2d30c-00
> 
> Development Mode Swapping to Development environment will display more detailed information about the error that occurred.
> 
> The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

使用开发环境，查看详细报错信息
